apiVersion: v1
kind: Namespace
metadata:
  name: denoapp
  labels:
    app.kubernetes.io/name: denoapp-deployment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: denoapp-deployment
  name: denoapp-deployment
  namespace: denoapp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: denoapp-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: denoapp-deployment
    spec:
      containers:
        - name: denoapp
          image: royalkingsax/denoapp3:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: deno-svc
  namespace: denoapp
spec:
  selector:
    app.kubernetes.io/name: denoapp-deployment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
